# Generated by Django 5.1.2 on 2024-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
